name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: target Wasm
      run: rustup target add wasm32-unknown-unknown
    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - uses: actions/checkout@v3
    - name: Build
      run: trunk build --release
        env:
          TRUNK_BUILD_PUBLIC_URL: ./
    - name: Run tests
      run: cargo test --verbose
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
