name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Deploy index to Gist
      uses: exuanbo/actions-deploy-gist@v1.1.4
      with:
        token: secrets.TOKEN
        gist_id: secrets.GIST_ID
        gist_description: a test yew app deployment
        file_path: dist/index.html 
    - name: Deploy style to Gist
      uses: exuanbo/actions-deploy-gist@v1.1.4
      with:
        token: secrets.TOKEN
        gist_id: secrets.GIST_ID
        gist_description: a test yew app deployment
        file_path: dist/style*.css
